Merge pull request #9075 in CLOUD/docs from support/fix-serial-console-vm-creation-2022-07-06 to develop
Squashed commit of the following:

commit bd99c81d75fa8b752a46333e196f858f39019f1d
Author: evgeniya-ch <evgeniya-ch@yandex-team.ru>
Date:   Wed Jul 13 20:10:09 2022 +0300

    fix in en

commit 53e41ae0b57b530f3d75f23610c30b01bae8ab85
Merge: 188b8bb9e27 741ead1eb49
Author: evgeniya-ch <evgeniya-ch@yandex-team.ru>
Date:   Wed Jul 13 19:53:00 2022 +0300

    Merge branch 'develop' of ssh://bb.yandex-team.ru/cloud/docs into support/fix-serial-console-vm-creation-2022-07-06

commit 188b8bb9e27b8c76d8777423b33486ff10febbdd
Author: Nikolai Kirillov <kirillovnl@yandex-team.ru>
Date:   Wed Jul 6 11:49:50 2022 +0000

    index.md edited online with Bitbucket
    Не корректная команда создания ВМ с передачей метаданных cloud-config , строку "  --ssh-key ~/.ssh/<имя открытого ключа>.pub \" необходимо исключить, так как это взаимоисключающая опция с --metadata-from-file.

    yc compute instance create \
    >   --name first-instance2 \
    >   --zone ru-central1-b \
    >   --network-interface subnet-name=net2-ru-central1-b,nat-ip-version=ipv4 \
    >   --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-2004-lts \
    >   --metadata-from-file ssh-keys=sshkeys.txt,user-data=metadata.yaml \
    >      --ssh-key ~/.ssh/id_ed25519.pub \
    >     --metadata serial-port-enable=1
    ERROR: --ssh-key flag conflicts with user-data metadata key. Please add your ssh key to user-data manually