Fix SyntaxError in sample code in boto.md
```
  File "/private/tmp/s3-test.py", line 9
    endpoint_url='https://storage.yandexcloud.net'
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```